services:
  - type: web
    name: cdls-ignite-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn cdls_ignite_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: MONGO_URI
        sync: false
    autoDeploy: false
